version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/markitdown"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/markitdown-mcp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/packages/markitdown-ocr"
    schedule:
      interval: "weekly"
